# Generated by Django 2.2.24 on 2022-01-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.BigIntegerField()),
                ('account_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
